### PR TITLE
clone source while merging

### PR DESCRIPTION
**Pull request by gagan-bansal**
Please check my issue #28

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@alexmngn and @gagan-bansal  hey! I'd love to make you a collaborator so you can merge this and other PRs and roll a new release! Please signup over at https://github.com/KyleAMathews/deepmerge/issues/25 and let's make this happen!

**Comment by TehShrike** [comment]
This would be a breaking change, but there are probably good arguments for it.  Anyone interested should weigh in on #28.

**Comment by gagan-bansal** [comment]
@KyleAMathews Thanks for the offer but because of the time constraints I will not be able to take this responsibility.

**Comment by KyleAMathews** [comment]
@gagan-bansal understood! I'm in the same boat :-)

**Comment by gagan-bansal** [comment]
Created a new pull request #44.

**Pull request closed without merging**
