### PR TITLE
Stop objects from being merged onto arrays

### LINKED ISSUE #65: Array to Object not working as expected
Having some problems with converting arrays to objects and discarding current array values.

```js
const deepmerge = require('deepmerge');

const x = {
  prop: ['hello'],
}

const y = {
  prop: {
    name: 'foo',
    value: 'bar'
  }
}

const result = deepmerge(x, y);

result.prop 
// expected { name: 'foo', value: 'bar' } but resulted in { 0: 'hello', name: 'foo', value: 'bar' }  

```

Is it possible to achieve what I'm looking for?

### PR DESCRIPTION
**Pull request by TehShrike**
This fix made a lot of sense, since we already had a test case and a logic flow specifically handling the "array onto object" case.

That makes me feel a bit better about releasing this as a patch version. though I may still do a feature version bump for paranoia's sake, since it is a decent behavioral change.

Fixes #65

### CODE REVIEW

**Comment by macdja38** [comment]
Definitaly makes sense not to merge Objects -> Arrays and Arrays -> Objects.

This does change functionality so I definitely agree with a major semvar version change.

**Comment by TehShrike** [comment]
Ah, all the way to major?  I was willing to think of this as a bug fix.

**Comment by macdja38** [comment]
I wish I knew how largely this would effect people. If they are using ^ in their packages.json to require this library then it would change functionality just based on an `npm update`. Has this always been broken or did it only happen recently?

**Comment by TehShrike** [comment]
Hard to say, but it's probably always been this way.  There was never a test asserting that behavior.

It's difficult to imagine anyone relying on being able to merge objects over arrays, but obligatory xkcd: [](https://xkcd.com/1172/)

**Comment by macdja38** [comment]
This is technically a breaking api change. so it would fall under a major patch version if we are strictly following http://semver.org/

**Comment by TehShrike** [comment]
The API signature is the same before and after this change, it's only a behavioral change.

**Comment by alexandernanberg** [comment]
Any updates on this? It's not currently breaking anything for me, just an annoyance but it would be nice to not have extra webpack bundled file (using deepmerge for webpack config) 😄

**Comment by TehShrike** [comment]
Thanks for the bump - published as 1.5.0.

**Pull request merged**
