### PR TITLE
Added TypeScript definitions

### PR DESCRIPTION
**Pull request by tobias-kuendig**
Added a TypeScript definitions file to be compatible with typescript.

### CODE REVIEW

**Comment by TehShrike** [comment]
My understanding is that non-typescript packages should have definitions contributed to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) instead of to the package itself, but I'm no expert.

**Comment by tobias-kuendig** [comment]
DefinitelyTyped got replaced by the @types repositories: https://github.com/types

You can either distribute the definition file with your package or via a types repository as described in the official documentation: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

If you distribute the file with your package everything "just works" when using it with typescript. Otherwise one has to install the separate @types repo manually.

**Comment by TehShrike** [comment]
Who will maintain this types file if the API of `deepmerge` ever changes in the future?  I don't use TypeScript, I don't have any way to test that the file works.

**Comment by tobias-kuendig** [comment]
Well, I guess that's the part where the community comes in. The file has to be maintained whether you distribute it with your package or via @types. I'll gladly register the file via @types if you don't want to have it bundled with your package.

**Comment by TehShrike** [comment]
That would be better.  👍

**Pull request closed without merging**
