### PR TITLE
Compare with null instead of strict with undefined

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by KyleAMathews** [comment]
@Kikobeats hey! I'd love to make you a collaborator so you can merge this and other PRs and roll a new release! Please signup over at https://github.com/KyleAMathews/deepmerge/issues/25 and let's make this happen!

**Comment by TehShrike** [comment]
This change causes some tests to break.  What's the motivation for this change?  Overwriting null values in the target would be a breaking change.  Is this a common use case?

**Comment by Kikobeats** [comment]
Actually I didn't remember... but basically compare with `== null` is the way for determinate if somehting exists (it means, if the value is `null` or `undefined`, it doesn't exist)

```js
function exists(v) { return v != null }
```

I think that I tried to express something like, but if this breaks tests (how do you know that breaks tests if travis integration isn't enabled? :P) feel free to close that.

**Comment by TehShrike** [comment]
I checked out your branch locally and ran the tests.

I know what the `== null` check does, matching both `null` and `undefined` - but those are two different values, so starting to treat them both as the same thing in this case could have unforeseen consequences.

At the very least we should probably have a couple new tests that show off the problems that this would solve.

**Comment by TehShrike** [comment]
oh, by the way, I know the PR was originally opened a while ago, so you may not remember the reasoning that prompted this change - no big deal, you can feel free to close this PR and open another issue or PR later if you remember the use case that needed this change. <3

**Pull request closed without merging**
