### PR TITLE
Create deepmerge.html

### PR DESCRIPTION
**Pull request by mkazlauskas**
This is an entrypoint for HTML Imports (Web Components)

### CODE REVIEW

**Comment by TehShrike** [comment]
I don't know anything about HTML imports - what would a programmatic test look like for this entrypoint?  Is there a way to run the tests with some kind of HTML Import bundler?

**Comment by mkazlauskas** [comment]
Well, it's as simple as `<link rel="import" href="deepmerge.html">`, which would import the script. The reason we don't want to use `<script>` directly is because different elements may import deepmerge and HTML imports takes care of making sure it doesn't get loaded multiple times.

**Comment by TehShrike** [comment]
Is there any web component bundler or something that we could use to test the entry point?

**Comment by mkazlauskas** [comment]
Sorry, I'm not sure what you're asking for. Do you want to do like automated tests? There is Polymer's tool called "vulcanize", which bundles all the web components and their scripts into a single html import file.

**Comment by TehShrike** [comment]
Yeah, that would do the trick.

I just don't want there to be any files in this package that people rely on, that don't have an automated test to keep them from getting broken in the future.

**Pull request closed without merging**
