### PR TITLE
Publish ESM + CJS + UMD modules

### LINKED ISSUE #58: loading with requirejs cause error
Trying to use html5-skin project (https://github.com/ooyala/html5-skin ) which has dependency of deepmerge. 
When loading html5-skin via requirejs, it causes `Mismatched` anonymous define() module: function ()`
Is there anything i need to do to use this library via requirejs... 
It works fine when loading wihtout requirejs..

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes #58

Drops the hardcoded UMD pattern, allowing bundlers to avoid grabbing it.

Moves the isMergeableObject function out to its own module, allowing other libraries to use the same algorithm for iterating over objects (see #61).

Also fixed some test jank by removing unused variables and adding a missing `var`

### CODE REVIEW

**Comment by macdja38** [comment]
The is-mergable-object repository seems to be missing a license? It should probably be under:
https://github.com/KyleAMathews/deepmerge/blob/master/license.txt
Also it seems to calculate `Object.prototype.toString.call(val)` twice, this could possibly be made faster by storing the result in a variable?

**Comment by TehShrike** [comment]
I changed the is-mergeable-object license to MIT to match deepmerge, and broke those `toString` calls out to a function.

**Comment by macdja38** [comment]
My problem was not that the code was write twice... it was that it was run twice... breaking them out into a function call does not reduce the number of  times they are run, it just ads the overhead of calling a function to them.

**Comment by TehShrike** [comment]
oh duh, lol.  I'll fix that

**Pull request merged**
