### PR TITLE
Fix the oldArrayMerge example

### LINKED ISSUE #83: oldArrayMerge() example code is non-executable
I'm trying to use the example `oldArrayMerge()` code [given in the README](https://github.com/KyleAMathews/deepmerge#arraymerge) but it won't run, as `cloneIfNecessary()` and `isMergeableObject()` are not defined. I see that `isMergeableObject()` can be got from another package (though it would be much neater if deepmerge could expose it as a pass-through), but `cloneIfNecessary()` doesn't seem to be defined anywhere.

My code depends on the pre-2.0.0 behaviour for array merging, so it would be really helpful to be able to reproduce this on the latest 2.0.0 code.

Thanks for this tool; it is very helpful, and I also appreciate the efforts you have gone to to explain how to keep the pre-2.0.0 behaviour; hope this issue report helps with that.

### PR DESCRIPTION
**Pull request by TehShrike**
Fixes #83

### CODE REVIEW

**Comment by TehShrike** [comment]
https://github.com/KyleAMathews/deepmerge/pull/84/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9R146

jsmd will check this assertion to make sure the example actually works.

**Comment by TehShrike** [comment]
Look reasonable?

@matatk

**Comment by matatk** [comment]
Thanks for the really quick turnaround on this.

Have tried it and, I'm not sure why, but it's not producing the same results that 1.5.2 was for me. I'm currently unsure as to exactly what the root of the problem is, but one thing it's definitely doing is turning a string into an object of (letter index, letter) pairs.

I was also wondering: given that deepmerge already uses is-mergeable-object, would it be possible for deepmerge to expose it so that I don't then need to add is-mergeable-object as an extra dependency?

**Comment by TehShrike** [comment]
mm, I'll bet that's due to `clone` defaulting to `true` now.  If you pass in `{ clone: true }` to 1.5.2, do you get the same string-spreading behavior?

**Comment by TehShrike** [comment]
ah nope, I mis-transcribed the clone function.  It shouldn't try to clone if the input isn't a mergeable object.

**Comment by TehShrike** [comment]
> I was also wondering: given that deepmerge already uses is-mergeable-object, would it be possible for deepmerge to expose it so that I don't then need to add is-mergeable-object as an extra dependency?

I made an issue #85 for that.

**Comment by matatk** [comment]
It's working fine now; thanks again, particularly for fixing this so quickly.

**Comment by TehShrike** [comment]
Published as 2.0.1

**Pull request merged**
