### PR TITLE
Improve options section of the readme

### PR DESCRIPTION
**Pull request by ArtskydJ**
- Clarify `arrayMerge`'s arguments.
- Fix `clone` heading level.

### CODE REVIEW

**Comment by TehShrike** [comment]
Looks good to me.  I wonder if those comments inside `concatMerge` should be assertion comments with the `=>`, just to guarantee they're correct?

**Comment by ArtskydJ** [comment]
Like this:
```js
destinationArray // => [1, 2, 3]
sourceArray // => [3, 2, 1]
options // => { arrayMerge: concatMerge }
```
?

**Comment by TehShrike** [comment]
Yeah, that should do it I think.

**Comment by ArtskydJ** [comment]
Done.

**Comment by TehShrike** [comment]
Published as 1.3.1.  Thanks!

**Pull request merged**
